#ifndef YVENCRYPTEDPROTOCOL_GLOBAL_H
#define YVENCRYPTEDPROTOCOL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(YVENCRYPTEDPROTOCOL_LIBRARY)
#  define YVENCRYPTEDPROTOCOLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define YVENCRYPTEDPROTOCOLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // YVENCRYPTEDPROTOCOL_GLOBAL_H
